# Build and create releases
name: "CI: Build and create releases"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.png'
      - '**.ico'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.png'
      - '**.ico'

env:
  BUILD_TYPE: Release
  CONAN_USER_HOME: "${{github.workspace }}/release/"
  CONAN_USER_HOME_SHORT: "${{github.workspace }}/release/short"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Deps
        run: pip install -r build_requirements.txt
      - name: Using the builtin GitHub Cache Action for .conan
        id: cache-conan
        uses: actions/cache@v3
        env:
          cache-name: cache-conan-modules
        with:
          path: ${{env.CONAN_USER_HOME}}
          key: ${{runner.os}}-builder-${{ env.cache-name }}
          restore-keys: ${{runner.os}}-builder-${{env.cache-name}}
      - name: Build & Test
        run: ./tools/scripts/build.ps1 -t -r -i
        shell: pwsh
