# Build and create releases
name: "CI: Build and create releases"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.png'
      - '**.ico'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.png'
      - '**.ico'

env:
  BUILD_TYPE: Release
  CONAN_USER_HOME: "${{github.workspace }}/release/"
  CONAN_USER_HOME_SHORT: "${{github.workspace }}/release/short"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019, ubuntu-latest, macos-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Deps windows & linux
        if: matrix.os != 'macos-latest'
        run: pip install -r build_requirements.txt
      - name: Install Deps mac os
        if: matrix.os == 'macos-latest'
        run: pip3 install -r build_requirements.txt
      - name: Config conan server
        run: |
          conan config set general.revisions_enabled=True
          conan remote add -i 0 custom-conan ${{secrets.CONAN_REMOTE}} False
          conan user -r custom-conan -p ${{secrets.CONAN_PASSWORD}} ${{secrets.CONAN_LOGIN_USERNAME}}
      - name: Enable Developer Command Prompt
        if: matrix.os == 'windows-2019'
        uses: ilammy/msvc-dev-cmd@v1.12.0
        with:
          arch: amd64
          vsversion: 2019
      - name: Build & Test
        run: ./tools/scripts/build.ps1 -r -u -t
        shell: pwsh
      - name: Create install
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: ./tools/scripts/build.ps1 -r -i
        shell: pwsh
      - name: Create a release
        if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.os == 'windows-2019' }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./out/build/release/bootstrap*.*
